replicaCount: 2

image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: sample-app.example.com
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Mi

configMap:
  APP_ENV: production
  APP_DEBUG: "false"

secret:
  DB_PASSWORD: cGFzc3dvcmQ=  # base64 encoded "password"

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


