apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to NGINX!</title>
    </head>
    <body>
        <h1>Success! The NGINX server is working!</h1>
    </body>
    </html>
